apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin-secret
type: "kubernetes.io/rbd"
data:
  # ceph auth get-key client.admin | base64
  key: QVFCWG5vaGVxdUxqRlJBQTdDbzBmTDdGNy8yY3dXMllhcFJHM3c9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-user-secret
type: "kubernetes.io/rbd"
data:
  # ceph auth add client.kube mon 'allow r' osd 'allow rwx pool=kube'
  # ceph auth get-key client.kube | base64
  key: QVFBYW40bGU0MXFGRkJBQUM4MjR0VHpJaXdFOVBjNGtra3BpekE9PQ==
